# Generated by Django 2.1.7 on 2019-03-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleObject',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Elo', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
