# Generated by Django 2.1.7 on 2019-03-29 07:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Elo child', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='sampleobject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='objectschild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapi.SampleObject'),
        ),
    ]
